export const CANDIDATE_TYPES = {
  SET_CANDIDATES: 'SET_CANDIDATES',
  SET_CANDIDATE_LOADING: 'SET_CANDIDATE_LOADING',
  SET_CANDIDATE_ERROR: 'SET_CANDIDATE_ERROR',
  ADD_CANDIDATE: 'ADD_CANDIDATE',
  UPDATE_CANDIDATE: 'UPDATE_CANDIDATE',
  DELETE_CANDIDATE: 'DELETE_CANDIDATE',
  SET_CURRENT_CANDIDATE: 'SET_CURRENT_CANDIDATE',
  CLEAR_CURRENT_CANDIDATE: 'CLEAR_CURRENT_CANDIDATE'
}; 