### Get All Attendance Data
GET  http://localhost:5000/data_kehadiran

### Create Attendance Data
POST  http://localhost:5000/data_kehadiran
Content-Type: application/json

{
    "bulan" : "April",
    "nik": "334455",
    "nama_pegawai": "Budi",
    "nama_jabatan": "Operator Produksi",
    "jenis_kelamin": "Male",
    "hadir": "2",
    "sakit": "1",
    "alpha": "1"
}

### UPDATE data kehadiran
PATCH  http://localhost:5000/data_kehadiran/update/4
Content-Type: application/json

{
    "hadir": "2",
    "sakit": "0",
    "alpha": "2"
}

### DELETE Attendance Data
DELETE http://localhost:5000/data_kehadiran/8