const DataAbsensiPegawai = [
    {
        id: 1,
        nik: "1218052110020002",
        namaPegawai: "Gilbert Hutapea",
        Gender: "Male",
        titleJabatan: "HRD",
        hadir: "22",
        sakit: "5",
        alpha: "3",
    },
    {
        id: 2,
        nik: "1218052110020003",
        namaPegawai: "Layla Siregar",
        Gender: "Female",
        titleJabatan: "Staff Marketing",
        hadir: "23",
        sakit: "4",
        alpha: "3",
    },
    {
        id: 3,
        nik: "1218052110020004",
        namaPegawai: "Zilong Sibarani",
        Gender: "Male",
        titleJabatan: "Admin",
        hadir: "24",
        sakit: "3",
        alpha: "3",
    },
    {
        id: 4,
        nik: "1218052110020005",
        namaPegawai: "Nana Silaban",
        Gender: "Female",
        titleJabatan: "Sales",
        hadir: "25",
        sakit: "2",
        alpha: "3",
    },
    {
        id: 5,
        nik: "1218052110020005",
        namaPegawai: "Nana Silaban",
        Gender: "Female",
        titleJabatan: "Non Staf",
        hadir: "26",
        sakit: "1",
        alpha: "3",
    },
    {
        id: 6,
        nik: "1218052110020005",
        namaPegawai: "Nana Silaban",
        Gender: "Female",
        titleJabatan: "Supervisi",
        hadir: "27",
        sakit: "0",
        alpha: "3",
    },
    {
        id: 7,
        nik: "1218052110020005",
        namaPegawai: "Nana Silaban",
        Gender: "Female",
        titleJabatan: "Designer",
        hadir: "28",
        sakit: "2",
        alpha: "2",
    },
    {
        id: 8,
        nik: "1218052110020005",
        namaPegawai: "Nana Silaban",
        Gender: "Female",
        titleJabatan: "Manager",
        hadir: "29",
        sakit: "1",
        alpha: "0",
    },
];

export default DataAbsensiPegawai;
